(()=>{'use strict';const data=window.TrialData,L=window.TrialLogic,$=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let cart=[],visible=[],current=0,timer;
const money=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:0}).format(n);
function notify(t){$('toast').textContent=t;$('toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('visible'),2400)}
function render(){visible=L.filterProducts(data.products,{country:$('country').value,category:$('category').value,query:$('search').value,sort:$('sort').value});$('count').textContent=visible.length+' / '+data.products.length+' znaczków';$('empty').hidden=!!visible.length;$('products').innerHTML=visible.map(p=>`<article class="product" data-id="${esc(p.id)}"><button class="product-image" data-open="${esc(p.id)}" aria-label="Obejrzyj ${esc(p.title)}"><span class="product-code">AT / ${esc(p.id)}</span><img src="art/${esc(p.id)}.svg" alt="Ilustracja: ${esc(p.title)}" loading="lazy"><span class="view">➚</span></button><div class="country-label">${esc(p.country)} · ${p.year}</div><h3>${esc(p.title)}</h3><div class="product-bottom"><span>${money(p.price)}</span><button class="add" data-add="${esc(p.id)}" ${cart.includes(p.id)?'disabled':''}>${cart.includes(p.id)?'W torbie ✓':'Do torby +'}</button></div></article>`).join('')}
function add(id){if(cart.includes(id)||!data.products.some(p=>p.id===id))return;cart.push(id);$('receipt').hidden=true;syncCart();render();if($('product-dialog').open)detail();notify('Znaczek dodany do torby')}
function syncCart(){$('cart-count').textContent=cart.length;$('cart-items').innerHTML=cart.map(id=>{const p=data.products.find(p=>p.id===id);return `<div class="cart-item"><img src="art/${id}.svg" alt="${esc(p.title)}"><div><strong>${esc(p.title)}</strong><br>${esc(p.country)} · ${money(p.price)}</div><button class="remove" data-remove="${id}" aria-label="Usuń ${esc(p.title)}">×</button></div>`}).join('')||'<p>Torba jest pusta. Odkryj kolekcję i wybierz swój znaczek.</p>';$('cart-total').textContent=money(L.cartTotal(data.products,cart));$('checkout').disabled=!cart.length}
function detail(){const p=visible[current];if(!p)return;$('detail-image').src=`art/${p.id}.svg`;$('detail-image').alt='Ilustracja: '+p.title;$('detail-country').textContent=p.country+' / '+p.category;$('detail-title').textContent=p.title;$('detail-meta').innerHTML=[['Rok',p.year],['Stan — przykład',p.condition],['Numer katalogu',p.id.toUpperCase()]].map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join('');$('detail-price').textContent=money(p.price);$('gallery-position').textContent=`${current+1} / ${visible.length}`;$('detail-add').disabled=cart.includes(p.id);$('detail-add').textContent=cart.includes(p.id)?'W torbie ✓':'Dodaj do torby ➚'}
for(const country of [...new Set(data.products.map(p=>p.country))]){const option=document.createElement('option');option.value=country;option.textContent=country;$('country').append(option);const b=document.createElement('button');b.className='country-card';b.dataset.country=country;b.innerHTML=`<span class="number">${String($('country-grid').children.length+1).padStart(2,'0')} / KRAJ</span><strong>${esc(country)} ➚</strong><small>${data.products.filter(p=>p.country===country).length} znaczki</small>`;b.onclick=()=>{$('country').value=country;$('category').value='';$('search').value='';render();$('catalog').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'})};$('country-grid').append(b)}
for(const c of data.categories){const o=document.createElement('option');o.value=c;o.textContent=c;$('category').append(o)}
for(const id of ['country','category','sort','search'])$(id).addEventListener(id==='search'?'input':'change',render);
$('clear').onclick=()=>{for(const id of ['country','category','search'])$(id).value='';$('sort').value='featured';render()};
$('products').onclick=e=>{const a=e.target.closest('[data-add]'),v=e.target.closest('[data-open]');if(a)add(a.dataset.add);if(v){current=visible.findIndex(p=>p.id===v.dataset.open);detail();$('product-dialog').showModal()}};
$('detail-add').onclick=()=>add(visible[current].id);$('next').onclick=()=>{current=(current+1)%visible.length;detail()};$('previous').onclick=()=>{current=(current-1+visible.length)%visible.length;detail()};
$('product-dialog').addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='ArrowRight')$('next').click();if(e.key==='ArrowLeft')$('previous').click()});
$('cart-open').onclick=()=>{syncCart();$('cart-dialog').showModal()};$('cart-items').onclick=e=>{const b=e.target.closest('[data-remove]');if(!b)return;cart=cart.filter(id=>id!==b.dataset.remove);$('receipt').hidden=true;syncCart();render()};
$('checkout').onclick=()=>{if(!cart.length)return;$('receipt-content').textContent=`Wybrano ${cart.length} znaczków. Wartość: ${money(L.cartTotal(data.products,cart))}. Płatność: nie pobrano.`;$('receipt').hidden=false};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());syncCart();render();
})();
