(()=>{'use strict';const $=id=>document.getElementById(id),D=window.TrialData,L=window.TrialLogic,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const audio=$('audio'),video=$('horizon-film'),reduced=matchMedia('(prefers-reduced-motion:reduce)');let selected=0,frame=0,eventSelected=null,playTicket=0;
$('brand-logo').onerror=()=>{$('brand-logo').hidden=true};if($('brand-logo').complete&&!$('brand-logo').naturalWidth)$('brand-logo').hidden=true;
function syncFilm(){frame=0;if(document.hidden||reduced.matches||!Number.isFinite(video.duration))return;const section=$('home'),start=section.offsetTop,end=start+section.offsetHeight-innerHeight,target=Math.min(Math.max(0,video.duration-.04),L.scrollTime(scrollY,start,end,video.duration));if(Math.abs(video.currentTime-target)>.04&&!video.seeking)video.currentTime=target;$('film-progress').style.width=(target/video.duration*100)+'%';$('film-frame').textContent='FRAME '+String(Math.round(target/video.duration*240)).padStart(3,'0')+' / 240';document.body.dataset.filmTime=target.toFixed(3)}
function schedule(){if(!frame&&!document.hidden)frame=requestAnimationFrame(syncFilm)}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);video.addEventListener('loadedmetadata',schedule);video.addEventListener('seeked',schedule);reduced.addEventListener('change',()=>{video.pause();schedule()});
function trackUI(){document.querySelectorAll('.track').forEach((b,i)=>{b.classList.toggle('active',i===selected);b.setAttribute('aria-pressed',String(i===selected))});$('track-title').textContent=D.tracks[selected].title}
function state(){const playing=!audio.paused;$('play').textContent=playing?'Ⅱ':'▷';$('play').setAttribute('aria-label',playing?'Wstrzymaj utwór':'Odtwórz utwór');$('audio-state').textContent=playing?'TERAZ ODTWARZANE':'GOTOWY DO ODSŁUCHU';document.body.dataset.playing=String(playing)}
function loadTrack(i){playTicket++;audio.pause();selected=(i+D.tracks.length)%D.tracks.length;audio.src=D.tracks[selected].src;audio.load();$('seek').value=0;$('elapsed').textContent='0:00';$('duration').textContent='0:00';$('audio-message').textContent='';trackUI();state()}
async function play(){if(!audio.paused){playTicket++;audio.pause();return}const ticket=++playTicket;try{await audio.play();if(ticket!==playTicket||document.hidden)audio.pause()}catch{if(ticket===playTicket)$('audio-message').textContent='Nie udało się rozpocząć odtwarzania. Spróbuj ponownie.'}state()}
$('play').onclick=play;$('next-track').onclick=()=>loadTrack(selected+1);$('previous-track').onclick=()=>loadTrack(selected-1);audio.volume=.65;$('volume').oninput=()=>audio.volume=Number($('volume').value);$('seek').oninput=()=>{if(Number.isFinite(audio.duration)&&audio.duration>0)audio.currentTime=Number($('seek').value)/1000*audio.duration};
for(const e of ['play','pause','ended'])audio.addEventListener(e,state);audio.addEventListener('error',()=>{$('audio-message').textContent='Nagranie jest niedostępne. Wybierz inny utwór.';state()});audio.addEventListener('loadedmetadata',()=>{$('duration').textContent=L.formatTime(audio.duration)});audio.addEventListener('timeupdate',()=>{const progress=audio.duration?audio.currentTime/audio.duration:0;$('seek').value=Math.round(progress*1000);$('elapsed').textContent=L.formatTime(audio.currentTime);document.querySelectorAll('#waveform i').forEach((b,i)=>b.classList.toggle('played',i/56<progress))});
$('waveform').innerHTML=Array.from({length:56},(_,i)=>`<i style="height:${12+Math.abs(Math.sin(i*2.31)*Math.cos(i*.28))*46}px"></i>`).join('');
$('track-list').innerHTML=D.tracks.map((t,i)=>`<button class="track" data-track="${i}" aria-pressed="false"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(t.title)}</b><span>${L.formatTime(t.duration)}</span></button>`).join('');$('track-list').onclick=e=>{const b=e.target.closest('[data-track]');if(b)loadTrack(Number(b.dataset.track))};
function renderEvents(){const list=L.filterEvents(D.events,$('city').value);$('events').innerHTML=list.map(e=>`<article class="event"><div class="event-date"><b>${esc(e.day)}</b>${esc(e.month)} ${esc(e.year)}</div><div><h3>${esc(e.title)}</h3><p>${esc(e.city)} / ${esc(e.venue)}</p></div><span>PRZYKŁAD · ${esc(e.type)}</span><button data-event="${esc(e.id)}" aria-label="Szczegóły ${esc(e.title)}">➚</button></article>`).join('')||'<p>Brak wydarzeń w wybranym mieście.</p>'}
for(const city of [...new Set(D.events.map(e=>e.city))]){const o=document.createElement('option');o.value=city;o.textContent=city;$('city').append(o)}$('city').onchange=renderEvents;$('events').onclick=e=>{const b=e.target.closest('[data-event]');if(!b)return;eventSelected=D.events.find(x=>x.id===b.dataset.event);$('event-name').textContent=eventSelected.title;$('event-detail').textContent=`${eventSelected.day}.${eventSelected.monthNumber}.${eventSelected.year} · ${eventSelected.city} · ${eventSelected.venue}`;$('event-dialog').showModal()};
$('calendar').onclick=()=>{if(!eventSelected)return;const e=eventSelected,date=e.year+e.monthNumber+e.day;const content=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Local Music Demo//EN\r\nBEGIN:VEVENT\r\nUID:${e.id}@local-demo.invalid\r\nDTSTAMP:20260920T000000Z\r\nDTSTART;VALUE=DATE:${date}\r\nSUMMARY:DEMO - ${e.title}\r\nDESCRIPTION:Test calendar entry - not a real concert\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;const url=URL.createObjectURL(new Blob([content],{type:'text/calendar'})),a=document.createElement('a');a.href=url;a.download='wydarzenie-testowe.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('contact-open').onclick=()=>$('contact-dialog').showModal();$('contact-form').onsubmit=e=>{e.preventDefault();$('contact-result').textContent='Szkic wiadomości — nie wysłano:\n'+$('contact-type').value+'\n'+$('contact-text').value};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
document.addEventListener('visibilitychange',()=>{if(document.hidden){playTicket++;audio.pause();video.pause();if(frame)cancelAnimationFrame(frame);frame=0}else schedule()});addEventListener('pagehide',()=>{playTicket++;audio.pause();video.pause()});loadTrack(0);renderEvents();schedule();
})();
