"""Versioned, curated instructions. No runtime project data or credentials."""
UPDATED='19.09.2026'


def topic(id,title,summary,steps,warning,href,action,keywords=''):
    return dict(id=id,title=title,summary=summary,steps=steps,warning=warning,href=href,action=action,keywords=keywords)


UPWORK_TOPIC = topic('upwork','Zlecenie z Upwork — jak rozpocząć?',
        'Pierwsze zlecenia mogą być małe, ale rozwój systemu obejmuje też trudniejsze projekty. Konta klientów prywatnych i płatności są późniejszym etapem.',
        ['Otwórz „Zlecenia Upwork” z pulpitu, Spatial lub wyszukiwarki. Korzysta z obecnej wspólnej sesji właściciela; logowanie hasłem pozostaje do wdrożenia.',
         'Na początek możesz wybrać przykład: godziny × stawka, przelicznik długości lub licznik słów. Uzupełni wyłącznie formularz, bez zapisu i modelu. To ćwiczenie, nie prawdziwe zlecenie. Własny opis klienta i kryteria wpisz bez sekretów; zapis tworzy projekt i cztery zadania.',
         'Gdy zasoby są dostępne, kliknij „Analizuj zakres lokalnym Qwenem”. Podczas wynajmu Vast.ai nie uruchamiaj modeli ani testów wykonawczych. Analiza ocenia dopasowanie i pytania, ale nie przyjmuje kontraktu i nie wysyła oferty.',
         'Odczytaj wynik. Przy niepewnym połączeniu odśwież projekt — zapisanej analizy nie trzeba uruchamiać od nowa. Błędy i ponowienia są również w historii Qwen w Centrum realizacji.',
         'Kliknij „Odbierz zakres i przejdź do wykonawcy”. Sprawdź specyfikację i pytania, odbierz etap analityka, a potem generuj pliki, uruchom testy i poprawki oraz przygotuj wydanie.'],
        'Wspierany profil: mała bezstanowa aplikacja Python stdlib, HTTP GET i HTML/CSS/JS. Konta, płatności, trwała baza, zewnętrzne API i hosting wymagają innych zdolności. Wynik modelu nie jest dowodem gotowości ani gwarancją zarobku.',
        '/os/upwork','Otwórz zlecenia Upwork','upwork oferta ogłoszenie zakres zarabianie')

OWNER=[
    topic('start','Pierwszy projekt — od czego zacząć?',
        'Zlecenie, wykonanie, testy, poprawki i wydanie mają osobne kroki. Nie trzeba otwierać wszystkich działów.',
        ['W górnym pasku użyj „Znajdź stronę lub funkcję” (Ctrl+K), np. wpisz „panel klienta” albo „realizacja”. Wybierz wynik. Skrót „Panel klienta” prowadzi do wejścia kodem; Twój podgląd jest osobnym wynikiem.',
         'Kliknij „Zaloguj właściciela” w górnym pasku i wpisz token raz. Następnie otwórz Realizację — sesja działa także w pozostałych panelach.',
         'Utwórz zlecenie: opisz cel, odbiorców, ograniczenia i mierzalne kryteria ukończenia; wybierz obszar firmy.',
         'Po wybraniu projektu zobaczysz „Twój następny krok”. Po przydziale zespołu użyj „Przygotuj bieżący etap”: otworzy zapisaną instrukcję, bez modelu. Po przerwie odśwież projekt; niezmieniony etap użyje tej samej instrukcji. Zmiana stanu wymaga odświeżenia, nie uruchamia kolejnego etapu.',
         'Historię Qwen filtruj według projektu. Opcja „Tylko oczekujące, trwające i niepewne” pokaże także stare nierozstrzygnięte wpisy. Qwen uruchamiaj dopiero przy dostępnych zasobach, nie podczas wynajmu Vast.ai.',
         'Po odebraniu specyfikacji przejdź do wykonawcy generującego pliki. W Budowie i testach uruchom aplikację oraz automatyczne poprawki.',
         'Po sprawdzeniu zakresu odbierz konkretną próbę i przygotuj wydanie. Treści dla klienta publikujesz osobno.'],
        'Obecny profil tworzy małe aplikacje Python z biblioteką standardową i HTML/CSS/JS. To nie wykonawca dowolnych zleceń ani automatyczna integracja Upwork.',
        '/os/work','Otwórz Realizację','onboarding zlecenie instrukcja start'),
    UPWORK_TOPIC,
    topic('source-edits','Jak podejrzeć i zmienić pliki projektu?',
        'Wieloplikowa edycja tworzy nową wersję źródeł, nie nadpisuje poprzedniej paczki.',
        ['Otwórz Budowę i testy z linku przy paczce w Centrum realizacji. Wczytaj wybraną paczkę.',
         'W sekcji „Pliki paczki” wybierz ścieżkę i otwórz plik. Źródła są tylko tekstem — nic się nie uruchamia.',
         'Edytuj plik i dodaj zmianę do szkicu. Możesz podać nową ścieżkę i dodać kolejne pliki. Istniejące rozpoznane testy są chronione.',
         'Podaj opis i zapisz nową wersję. Przy niepewnej odpowiedzi ponów ten sam szkic; nie zmieniaj jego treści przed rozstrzygnięciem zapisu.',
         'Otwórz nową paczkę z otrzymanego linku. Stare wyniki testów i odbioru jej nie zatwierdzają.'],
        'Szkic nie przetrwa zamknięcia karty. Zapis wielu katalogów nie oznacza obsługi przez obecny runner. Podczas wynajmu Vast.ai nie uruchamiaj Qwena ani kontenerów.',
        '/os/build','Otwórz pliki i wersje','źródła katalogi pliki edytor kod wersja poprawka'),
    topic('multifile','Jak uruchomić testy projektu z wieloma modułami?',
        'Profil wielomodułowy obsługuje testy, podgląd, odbiór konkretnej paczki i wydanie ZIP z instrukcjami dla klienta.',
        ['Otwórz Budowę i testy i wczytaj paczkę z katalogami.',
         'Wybierz „Sprawdź strukturę i składnię — bez uruchamiania”. To odczyt tej wersji źródeł, nie model ani test kontenerowy.',
         'Lista pokaże brakujące pliki, błędy składni i niedozwolone ścieżki. Popraw źródła w nowej paczce i sprawdź ją ponownie.',
         'Dla zgodnego układu zaznacz zgodę i wybierz „Uruchom aplikację i testy w izolacji”. Po przerwie odśwież historię przed ponownym uruchomieniem.',
         'Przeczytaj raport. Przy zaliczonym wykonaniu wybierz „Otwórz aplikację w izolacji”, sprawdź formularz, a następnie pobierz ZIP kandydata. Jeśli testy nie przeszły, otwórz pliki, zapisz poprawioną paczkę i przetestuj nową wersję.',
         'Przy zaliczonym wykonaniu wybierz „Odbierz lub wycofaj odbiór tej paczki”. Opisz sprawdzony zakres i dowody, wybierz decyzję i potwierdź. Potem sprawdź gotowość i pobierz zatwierdzone wydanie.',
         'Profil przewiduje app.py, index.html, README.md, moduły w modules/, testy unittest w tests/ i lokalne zasoby static/. Pakiety Pythona wymagają __init__.py.'],
        'Odbiór paczki nie zamyka zadania i nie publikuje klientowi. Nowa wersja, nowy test, zmiana zakresu lub wycofanie decyzji unieważniają wcześniejszą gotowość. Podgląd: tylko bezstanowe GET /api/nazwa. Automatyczne poprawki i wykonanie wybranego planu HTTP starego cyklu nie są jeszcze obsługiwane dla nowego profilu.',
        '/os/build','Sprawdź strukturę paczki','wiele modułów katalogi Python unittest walidacja składnia runner'),
    topic('graphics','Jak wygenerować grafikę do projektu?',
        'Lokalny ComfyUI przygotowuje pojedynczy obraz do istniejącego zadania. Qwen nie musi pisać kodu workflow.',
        ['Uruchom ComfyUI ze skrótu na pulpicie. Wagi Z-Image Turbo muszą być dostępne; nie są pobierane automatycznie.',
         'W Centrum realizacji przy zadaniu kliknij „Grafika do tego zadania” albo wyszukaj „Grafika projektowa”. Korzystaj ze wspólnej sesji właściciela.',
         'Wczytaj zatwierdzone i niezablokowane zadanie. Wpisz opis, ustaw seed wariantu i potwierdź jedną generację 768×512 / 8 kroków.',
         'Historia odbiera wynik przez maksymalnie pięć minut w otwartej karcie. Później lub po przerwie kliknij „Odśwież historię”. Nie ponawiaj niepewnego wysłania.',
         'Obejrzyj grafikę i raport. Zaakceptuj albo odrzuć konkretną wersję. Pobranie PNG jest dla właściciela; nie publikuje go klientowi.'],
        'Kontrola techniczna obejmuje format, rozmiar i niejednorodność pikseli, nie jakość artystyczną ani licencję. Akceptacja grafiki nie kończy zadania. Nie uruchamiaj równocześnie modeli GPU poza aplikacją. Brak historii nie dowodzi, że generowanie zostało przerwane.',
        '/os/media','Otwórz grafikę projektową','comfyui grafika obraz generator z-image multimedia'),
    topic('access','Token właściciela — co wpisać?',
        'Token jest kluczem dostępu do operacji wewnętrznych, nie hasłem klienta ani instrukcją dla Qwena.',
        ['W górnym pasku pulpitu wybierz „Zaloguj właściciela”. Użyj tokena skonfigurowanego dla tej instalacji; nie wpisuj przypadkowej wartości.',
         'Wpisz token tylko w oknie logowania. Sesja pozwala przechodzić między Realizacją, Budową, Odbiorem, Publikacjami, Historią i Podglądem klienta bez ponownego wklejania.',
         'Sesja trwa najwyżej 8 godzin. „Wyloguj właściciela”, restart serwera lub zmiana tokena kończy dostęp. Inne urządzenie i inny adres panelu wymagają własnego logowania.',
         'Dawne pola tokena pozostają trybem jednorazowego dostępu, jeśli nie korzystasz ze wspólnego logowania. Nie umieszczaj tokena w linkach, kodzie, opisach ani zrzutach.'],
        'Przeglądarka przechowuje jedynie osobny identyfikator sesji w HttpOnly cookie, nie token API. Klient potrzebuje własnego kodu projektu. HTTP działa tylko lokalnie; zdalna sesja wymaga HTTPS.',
        '/os/work','Wróć do Realizacji','logowanie hasło kod autoryzacja 401 403'),
    topic('agents','Dlaczego agent lub dział jeszcze nie pracuje?',
        'Role w drzewie to odpowiedzialności. Ich obecność nie oznacza uruchomionego modelu.',
        ['W wyszukiwarce wybierz „Agenci działów”. W sekcji zespołów rozwiń dział: zobaczysz specjalizacje, instrukcje i stan ostatnich wykonań przypisanych zadań. Samo wejście niczego nie uruchamia.',
         '„Pokaż zadania tego działu” wyświetla jego zlecenia i blokady. „Zleć pracę temu działowi” otwiera formularz z wybraną gałęzią. Po zapisaniu zakresu przydziel kierownika i agentów.',
         'Przy zadaniu sprawdź wykonawcę, kontrolera oraz blokady poprzedniego etapu.',
         'Najpierw odbierz wymagany wcześniejszy wynik. Następnie przygotuj instrukcję gotowego zadania i uruchom lokalny Qwen.',
         'Sprawdź historię wykonań zamiast zakładać, że animacja lub procent oznaczają pracę w tle.'],
        'Nie usuwaj blokad przez zmianę statusów w bazie. Odebranie jednego zlecenia nie oznacza ukończenia całego działu.',
        '/os/work?teams=1','Zobacz zespoły i zadania','kierownik brain mrówki zależności zero procent'),
    topic('qwen','Jak wygenerować pliki aplikacji?',
        'Wybór profilu kodu odróżnia aplikację od zwykłej odpowiedzi tekstowej.',
        ['Przy gotowym etapie wykonawcy kliknij „Przygotuj instrukcję”. Zakres/specyfikacja muszą być wcześniej odebrane.',
         'Wybierz „Qwen: wygeneruj pliki aplikacji Python” albo „Qwen: zbuduj aplikację z osobnymi modułami”. Opcjonalne testy po generowaniu wymagają zaznaczenia odpowiedniej zgody.',
         'W historii Qwena otwórz odnośnik do paczki. Nowa paczka ma własne ID i sumę kontrolną.',
         'Wariant modułowy rozdziela backend, logikę, interfejs i testy. W Budowie i testach sprawdź działanie, odbierz konkretną paczkę i przygotuj ZIP. Nie obsługuje jeszcze automatycznej naprawy, bazy danych, logowania ani zależności pip.',
         'Jeśli model nie utworzył paczki, sprawdź błąd w historii; nie traktuj niepustej odpowiedzi jako działającej aplikacji.'],
        'Stara kolejka próbna jest symulacją. Zamknięcie karty nie potwierdza anulowania inferencji, a ponowienie niepewnego wyniku wymaga sprawdzenia historii.',
        '/os/work','Otwórz lokalnego Qwena','model pliki generowanie JSON paczka'),
    topic('api-contract','Jak sprawdzić powiązanie danych z API?',
        'Diagnostyka próbki JSON wykrywa brakujące pola, złe typy i puste wartości. Bez połączenia z usługą klienta i bez Qwena.',
        ['Otwórz Zlecenia Upwork, zaloguj właściciela i wczytaj zlecenia. Znajdź „Diagnostyka odpowiedzi API — bez sieci”.',
         'Wklej zanonimizowany JSON oraz odczytany i oczekiwany status HTTP. Nie wklejaj tokenów ani danych osobowych.',
         'Wpisz powiązania: name, pointer (np. /data/items/0/name), expected_type. Możesz zacząć od przycisku „Wstaw przykład syntetyczny”.',
         'Kliknij „Sprawdź próbkę i powiązania”. Zobacz brakujące pola i różnice typów. Popraw próbkę lub kontrakt świadomie, następnie sprawdź ponownie.',
         'Po zakończeniu wyczyść próbkę. Formularz nie zapisuje jej do projektu ani przeglądarkowego magazynu.'],
        'Zgodna próbka nie dowodzi działania API, autoryzacji, CORS, przeglądarki ani integracji. Nie jest raportem testowym dopuszczającym wydanie. Narzędzie nie wysyła wiadomości i nie modyfikuje kont klienta.',
        '/os/upwork','Otwórz diagnostykę API','JSON mapowanie tablica integracja WeWeb Xano Airtable kontrakt'),
    topic('preview','Aplikacja nic nie robi po otwarciu index.html',
        'Aplikacja serwerowa potrzebuje działającego API. Sam plik HTML z dysku go nie uruchamia.',
        ['Otwórz Budowę i testy, zaloguj właściciela, jeśli sesja wygasła, i znajdź zaliczone wykonanie odpowiedniej paczki.',
         'Kliknij „Otwórz aplikację w izolacji”. Wpisz dane i użyj formularza w podglądzie.',
         'Jeżeli brakuje nowych przycisków lub skryptów, odśwież panel Ctrl+Shift+R i ponownie otwórz podgląd.',
         'Zapisz numer paczki i dokładny komunikat, jeśli podgląd zwraca błąd.'],
        'Podgląd obsługuje bezstanowe żądania GET. Nie jest hostingiem z kontami, bazą, zapisem danych ani obsługą POST.',
        '/os/build','Otwórz Budowę i testy','kalkulator nie liczy index html formularz ładowanie'),
    topic('automatic','Testy i automatyczne naprawy bez ręcznego poprawiania',
        'Jeden start uruchamia cykl test → poprawka Qwen → nowa wersja → ponowny test.',
        ['Przy najnowszej paczce Qwen oczekującej na odbiór kliknij „Testuj i napraw automatycznie”.',
         'Potwierdź cały cykl. Po wykryciu błędu programu system przekaże log i źródła Qwenowi, zapisze poprawkę i ponowi testy.',
         'W „Automatycznej kontroli i naprawie” odśwież cykle, aby zobaczyć kroki oraz wynikową paczkę.',
         'Użyj zatrzymania po bieżącej operacji, jeśli nie chcesz dalszych prób. Po przerwie w pracy serwera wznów zapisany cykl z historii.'],
        'Maksymalnie dwie poprawki i trzy zestawy testów, deadline 15 minut. Bazowych testów nie wolno osłabiać. Zaliczenie zestawu nie potwierdza wszystkich wymagań biznesowych ani wyglądu.',
        '/os/build','Otwórz automatyczne naprawy','testy naprawa cykl retry limit failed passed'),
    topic('revision','Jak zgłosić zmianę, której testy nie wykrywają?',
        'Użyj formularza poprawki, gdy chodzi np. o opis, zachowanie lub wymaganie poza obecnym zestawem testów.',
        ['Przy wyniku testów wybierz „Zgłoś poprawkę do tej wersji”.',
         'Opisz problem, oczekiwany rezultat i sposób odtworzenia. Wskaż konkretną wersję, nie ogólne „nie działa”.',
         'W razie potrzeby zaznacz testy po generowaniu. Potwierdź skierowanie bieżącego wyniku do poprawy.',
         'Sprawdź nową paczkę w historii poprawek. Wcześniejsze źródła pozostają zachowane.',
         'W Budowie i testach użyj „Porównaj pliki z wcześniejszą wersją”, wybierz paczkę bazową i „Pokaż zmiany”. Przy zmienionym pliku możesz odczytać różnice; kod nie jest uruchamiany. Porównanie dostępne także po samym wczytaniu paczki, bez testów.'],
        'Formularz dotyczy najnowszej próby oczekującej na odbiór. Rozwój już zamkniętego zadania wymaga osobnego zadania.',
        '/os/build','Zgłoś poprawkę','zmiana uwagi wygląd wersja'),
    topic('release','„Wydanie wstrzymane” — co to oznacza?',
        'Testy, odbiór właściciela i publikacja klientowi są różnymi decyzjami.',
        ['Przeczytaj powód w „Sprawdź gotowość do przekazania”. Może brakować odbioru, aktualnego testu albo zgodności wersji.',
         'Jeżeli brakuje odbioru, otwórz „Odbiór zadania” i podaj wskazane ID. Aktywna sesja zastępuje ponowne wpisanie tokena. Sprawdź wyświetloną próbę, wynik testów i kryteria zakresu.',
         'Jeśli wynik spełnia zakres, wpisz uzasadnienie i dowody, potwierdź decyzję oraz wybierz „Zatwierdź wynik”.',
         'Wróć do Budowy i testów, ponownie sprawdź gotowość i przygotuj zatwierdzone wydanie.'],
        'Nie zatwierdzaj tylko po to, aby zniknął komunikat. ZIP kandydata nie jest zatwierdzonym wydaniem. Pobranie ZIP nie wysyła go klientowi i nie wdraża aplikacji.',
        '/os/review','Otwórz odbiór','wydanie wstrzymane akceptacja zatwierdzenie zip download'),
    topic('requirements','Jak sprawdzić konkretne wymagania klienta?',
        'Ogólne zaliczenie testów nie oznacza, że sprawdzono wszystkie wymagania produktu.',
        ['W Budowie i testach wybierz zapisaną paczkę i kliknij „Sprawdź wersję” — bez uruchamiania.',
         'Otwórz „Sprawdź wymagania klienta dla tej wersji”. Każde wymaganie ma osobny wynik kontroli.',
         'Zapisz co faktycznie sprawdzono, wejście, oczekiwany i rzeczywisty wynik. Opcjonalnie powiąż raport testów tej paczki.',
         'Potwierdź własną obserwację. Nowa paczka nie dziedziczy ocen starej wersji, a zmieniony zakres wymaga ponownej kontroli.'],
        'To ręczna weryfikacja, nie automatyczny dowód pokrycia wymagania testem. Nie zmienia odbioru ani postępu. W czasie wynajmu nie uruchamiaj obciążających kontroli; zapisuj tylko faktycznie wykonane obserwacje.',
        '/os/build','Sprawdź wymagania','wymagania kryteria dowody testy weryfikacja zakres'),
    topic('acceptance-examples','Automatyczne sprawdzanie konkretnych wyników aplikacji',
        'Zapisz niezmienne przykłady HTTP, aby model poprawiał aplikację względem ustalonego wyniku, nie zmieniał oczekiwań.',
        ['W Budowie i testach wybierz paczkę i otwórz „Przygotuj automatyczne sprawdzanie wymagań”.',
         'Wskaż wymaganie, ścieżkę GET, status HTTP i ewentualnie pole oraz oczekiwaną wartość JSON. Dodaj 1–4 przykłady.',
         'Zapisz plan. To nie uruchamia modelu ani kontenera. Podczas wynajmu wykonanie nowej funkcji pozostaje wyłączone.',
         'Po bezpiecznym odblokowaniu i pilocie można uruchomić cykl z wybranym planem. Błąd aplikacji trafia do poprawy i tych samych testów; wyniki są w historii cyklu.',
         'Wybranie planu do cyklu czyni go warunkiem odbioru i wydania. Niekompletne, niezaliczone lub nieaktualne dowody blokują odbiór; sam szkic planu nie blokuje.'],
        'Tylko bezstanowe GET, bez kont i zapisów POST. Zaliczony przykład nie potwierdza całego wymagania ani odbioru klienta. Nową ścieżkę sprawdzono na atrapach, nie w rzeczywistym pilocie podczas wynajmu.',
        '/os/build','Przygotuj przykłady odbioru','wymagania przypadki HTTP JSON testy oczekiwany wynik automatyczna naprawa'),
    topic('handoff','Jak przekazać aplikację klientowi na Upwork?',
        'Zatwierdzone wydanie zawiera samodzielną instrukcję klienta po polsku i angielsku.',
        ['W Budowie i testach sprawdź gotowość konkretnej wersji, odbierz wynik i przygotuj wydanie.',
         'Przy tym wykonaniu wybierz „Instrukcja klienta i wiadomość do Upwork”. Odczyt nie uruchamia modelu ani kontenera.',
         'Przejrzyj checklistę i szkic wiadomości EN. Dopasuj go do rzeczywistych ustaleń, nie dopisuj niepotwierdzonych obietnic.',
         'Pobierz zatwierdzony ZIP. Instrukcje CLIENT-START-HERE i metryki DELIVERY-SUMMARY są w środku w wersjach EN/PL. Metryka pokazuje pliki, wersję, zakres potwierdzonych kontroli i granice dowodów.',
         'Sam przekaż pliki na Upwork. Klient uruchamia aplikację serwerową według instrukcji; nie otwiera index.html dwuklikiem.'],
        'To szkic przekazania, nie wysyłka, wdrożenie ani odbiór klienta. Instrukcje dotyczą tylko profilu python-web-v1. Pobranie dokumentów nie oznacza zamknięcia projektu.',
        '/os/build','Otwórz wydania','upwork przekazanie klient instrukcja dokumentacja wiadomość handoff'),
    topic('clients','Publikacje, historia i podgląd klienta',
        'Klient widzi tylko informacje, które świadomie udostępnisz, nie wewnętrzne zadania i logi.',
        ['W Publikacjach przygotuj opis, postęp, etapy, rezultaty i kryteria dla klienta. Sprawdź treść przed potwierdzeniem.',
         'Utwórz czasowy dostęp. Kod pokazuje się przy utworzeniu; przekaż go bezpiecznym kanałem, nie jako fragment adresu.',
         'W „Historii klientów” wybierz udostępnienie, przejrzyj wersje, decyzje i zarejestrowane otwarcia etapów.',
         'Własny podgląd otwieraj przez „Podgląd klienta” ze wspólną sesją lub tokenem właściciela. Nie potrzebujesz kodu klienta i nie wysyłasz decyzji w jego imieniu.'],
        'Aktualizacja publikacji zastępuje cały opis i etapy, nie odnawia kodu. Materiały klienta są obecnie opublikowanymi tekstami; nie automatycznym transferem ZIP ani aplikacją na żywo.',
        '/os/clients','Otwórz historię klientów','klient publikacja kod historia preview udostępnienie'),
    topic('trouble','Błąd, przerwane połączenie lub niepewny stan',
        'Najpierw ustal, co serwer już zapisał. Wielokrotne nowe zgłoszenia mogą stworzyć osobne operacje.',
        ['Odśwież historię modelu, testów lub cykli i znajdź ten sam identyfikator operacji.',
         'Przy błędzie dostępu sprawdź właściwy token. Przy konflikcie wersji wczytaj aktualne dane.',
         'Niepewne wykonanie kontenera wymaga sprawdzenia stanu i bezpiecznego sprzątania przez istniejący panel — nie wyłączania wszystkich procesów.',
         'Przekaż administratorowi: nazwę strony, ID zadania/paczki, czas, dokładny komunikat i kroki odtworzenia. Usuń tokeny oraz dane klienta ze zrzutów.'],
        'Nie zmieniaj ręcznie bazy ani konfiguracji izolacji, żeby ominąć błąd. Automatyczna kontrola nie naprawia dowolnych awarii hosta.',
        '/os/build','Sprawdź historię wykonania','pomoc błąd 409 500 503 uncertain timeout brak danych'),
]

CLIENT=[
    topic('start','Pierwsze wejście do projektu',
        'Otwórz adres przestrzeni projektu otrzymany od wykonawcy.',
        ['Przygotuj czasowy kod dostępu przekazany przez wykonawcę.',
         'Wpisz go w pole „Kod dostępu otrzymany od wykonawcy” i wybierz „Otwórz projekt”.',
         'Sprawdź nazwę projektu, opublikowany postęp i „Najbliższy krok”.',
         'Po zakończeniu korzystania wybierz „Wyloguj”. Po opuszczeniu strony może być potrzebne ponowne wpisanie kodu.'],
        'W tej wersji korzystasz z kodu, nie konta e-mail i hasła. Pomoc nie wymaga kodu i nie służy do jego przesyłania.',
        '/client','Otwórz panel projektu','logowanie login email hasło token kod konto'),
    topic('access','Kod nie działa lub wygasł',
        'Dostęp może wygasnąć albo zostać cofnięty przez wykonawcę.',
        ['Sprawdź, czy otwierasz właściwy adres i czy kopiujesz pełny kod bez dodatkowych znaków.',
         'Jeśli nadal nie działa, poproś wykonawcę o sprawdzenie ważności dostępu lub nowy kod.',
         'Podaj nazwę projektu i treść komunikatu, ale nie wysyłaj kodu w zgłoszeniu ani na zrzucie ekranu.'],
        'Nie ma jeszcze samodzielnego resetowania hasła ani odnawiania dostępu płatnością w tym panelu.',
        '/client','Wróć do logowania','wygasły odmowa dostęp błąd hasło reset'),
    topic('workflow','Jak czytać workflow i postęp?',
        'Workflow przedstawia etapy budowy opublikowane dla Twojego projektu.',
        ['W menu po lewej wybierz „Workflow”, a następnie interesujący etap.',
         'Przeczytaj zakres, udostępniony rezultat i kryteria ukończenia.',
         'Przechodź między etapami przyciskami „Poprzedni etap” i „Następny etap”.',
         'Sprawdź datę aktualizacji. „Odśwież dane” pobiera najnowszą publikację; na widocznej karcie dane odświeżają się też okresowo.'],
        'Widzisz opublikowany stan, nie transmisję tworzenia kodu na żywo. Procent określa wykonawca; nie jest automatycznie liczbą zielonych etapów.',
        '/client','Zobacz projekt','procent plan etapy status zablokowany aktualizacja'),
    topic('materials','Gdzie są materiały i gotowa aplikacja?',
        'Sekcja „Materiały” zbiera opublikowane opisy i fragmenty rezultatów.',
        ['Otwórz „Materiały” w menu projektu.',
         'Wybierz rezultat i przeczytaj jego opis oraz powiązany etap.',
         'Jeśli potrzebujesz działającego podglądu, plików lub instrukcji uruchomienia, uzgodnij ich przekazanie z wykonawcą.'],
        'Ta wersja panelu nie zapewnia automatycznego pobierania aplikacji ani uruchamiania jej w materiałach. Brak materiału może oznaczać, że jeszcze go nie opublikowano.',
        '/client','Otwórz materiały projektu','pobierz zip pliki aplikacja download pusto'),
    topic('feedback','Jak zgłosić poprawkę lub zaakceptować etap?',
        'Decyzja dotyczy wskazanej opublikowanej wersji etapu.',
        ['Wybierz „Do odbioru” i etap udostępniony do oceny.',
         'Sprawdź materiał i kryteria. Wybierz prośbę o poprawki albo akceptację.',
         'Napisz konkretny komentarz: co robisz, jaki jest rezultat i czego oczekujesz. Nie wpisuj haseł ani innych sekretów.',
         'Zaznacz potwierdzenie i wyślij decyzję. Przy zmianie wersji odśwież dane i oceń nową treść przed wysłaniem.'],
        'Jedna decyzja na wersję etapu. Zmianę decyzji uzgodnij z wykonawcą. Wysłanie uwag nie uruchamia samo w sobie automatycznej naprawy.',
        '/client','Przejdź do odbiorów','reklamacja poprawki uwagi zgłoszenie akceptacja komentarz'),
    topic('requirements','Jak przekazać wymagania i uzyskać pomoc?',
        'Przygotuj opis, który pozwala odtworzyć potrzebę lub problem.',
        ['Opisz cel projektu, oczekiwane zachowanie i ważne ograniczenia.',
         'Przy błędzie podaj kroki, oczekiwany i uzyskany rezultat oraz nazwę etapu. Dołącz zrzut bez kodu dostępu i danych wrażliwych.',
         'Uwagi do etapu wyślij przez „Do odbioru”. Pozostałe wymagania i pliki przekaż uzgodnionym kanałem kontaktu z wykonawcą.'],
        'Pomoc jest instrukcją, nie czatem z konsultantem. Panel nie ma jeszcze osobnego formularza nowego zlecenia, przesyłania plików, płatności ani faktur.',
        '/client','Wróć do projektu','kontakt wsparcie wymagania zamówienie czat płatności faktura'),
    topic('privacy','Kto widzi moją aktywność?',
        'Wykonawca widzi wybrane zdarzenia otwarcia projektu i nawigacji oraz świadomie wysłane decyzje.',
        ['Traktuj kod jako klucz do udostępnionego projektu i nie publikuj go.',
         'Przed wysłaniem komentarza sprawdź jego treść — zostanie udostępniony wykonawcy.',
         'Po pracy na wspólnym urządzeniu wyloguj się i zamknij kartę.'],
        'Nie zapisujemy klawiszy ani niewysłanych formularzy. Aktywność jest przypisana do kodu, nie jest dowodem tożsamości, przeczytania treści ani podpisem elektronicznym.',
        '/client','Wróć do projektu','prywatność bezpieczeństwo dane historia aktywność'),
]
